api/urls.py
from django.conf.urls               import url, include
from rest_framework                 import routers
from rest_framework.renderers       import CoreJSONRenderer
from api.serializers                import *

import api.views as views


router = routers.DefaultRouter(
    schema_title="Forms API",
    schema_renderers=[ CoreJSONRenderer ],
)

router.register( r'forms', views.FormViewSet )


urlpatterns = [
    url( r'^', include( router.urls )),
]

feedback/urls.py
from   django.conf.urls                 import include, url
from   django.contrib.auth.decorators   import login_required
from   django.http                      import HttpResponseRedirect
from   django.views.generic.base        import RedirectView
import views
import signals

app_name = 'forms'

urlpatterns = [
    url(r'^$',                                              lambda x: HttpResponseRedirect( "admin/" ) ),

    url(r'^admin/$',                                        login_required( views.ProjectList.as_view()        ),  name="project_list" ),
    url(r'^admin/import/$',                                 login_required( views.ImportProject.as_view()      ),  name="import" ),
    url(r'^admin/export/(.+)/$',                            login_required( views.ExportProject.as_view()      ),  name="export" ),
    url(r'^admin/newform/$',                                login_required( views.NewEditProject.as_view()     ),  name="new_project" ),
    url(r'^admin/editform/(.+)/reorder/$',                  login_required( views.ReorderQuestions.as_view()   ),  name="reorder_questions" ),
    url(r'^admin/editform/(.+)/delete/$',                   login_required( views.DeleteProject.as_view()      ),  name="delete_project" ),
    url(r'^admin/editform/(.+)/clear/$',                    login_required( views.ClearProject.as_view()       ),  name="clear_project" ),
    url(r'^admin/editform/(.+)/copyquestions/$',            login_required( views.CopyQuestions.as_view()      ),  name="copy_questions" ),
    url(r'^admin/editform/(.+)/$',                          login_required( views.NewEditProject.as_view()     ),  name="edit_project" ),

    url(r'^admin/newquestion/(.+)/$',                       login_required( views.NewEditQuestion.as_view()    ),  name="new_question" ),
    url(r'^admin/editquestion/(.+)/(.+)/delete/$',          login_required( views.DeleteQuestion.as_view()     ),  name="delete_question" ),
    url(r'^admin/editquestion/(.+)/(.+)/$',                 login_required( views.NewEditQuestion.as_view()    ),  name="edit_question" ),
    url(r'^admin/editquestion/$',                           login_required( views.NewEditQuestion.as_view()    ),  name="edit_question_url_prefix" ),

    url(r'^admin/answers/.+?/(.+?)/$',                      login_required( views.AnswersEdit.as_view()        ),  name="answers_edit" ),
    url(r'^admin/answers/(.+?)/$',                          login_required( views.AnswersList.as_view()        ),  name="answers_list" ),
    url(r'^admin/answers/$',                                login_required( views.AnswersFormList.as_view()    ),  name="answers_form_list" ),

    url(r'^admin/data/(.+)/(summary|list)/?(csv)?/$',       login_required( views.FeedbackData.as_view()       ),  name="feedback_data" ),
    url(r'^admin/data/(.+)/answer/$',                       login_required( views.FeedbackAnswers.as_view()    ),  name="feedback_answers" ),
    url(r'^chart(/(?P<pk>.+))?(/(?P<charttype>.+))?/$',     login_required( views.Chart.as_view()              ),  name="feedback_chart" ),

    url(r'^formlist.json/$',                                login_required( views.FormList.as_view()           ),  name="form_list" ),
    url(r'^unique/reference/(.+)$',                         login_required( views.UniqueReference.as_view()    ),  name="unique_reference" ),

    url(r'^unique/$',                                       views.unique,                                          name="unique" ),

    url(r'^(.+)/closed/$',                                  views.thanks,              {"template":"closed.html"}, name="closed" ),
    url(r'^(.+)/thanks/$',                                  views.thanks,              {"template":"thanks.html"}, name="thanks" ),
    url(r'^(.+)/maxed/(?:(.+)/)?$',                         views.Maxed.as_view(),                                 name="maxed" ),
    url(r'^(.+)/duplicate/(?:(.+)?)/$',                     views.Duplicate.as_view(),                             name="duplicate" ),

    url(r'^(.+)/$',                                         views.Questionnaire.as_view(),                         name="questionnaire" ),
]

project/urls.py
from django.conf.urls.static    import static
from django.conf.urls           import include, url
from django.contrib.auth        import logout
from django.contrib             import admin
from django.http                import HttpResponseRedirect
from django.shortcuts           import redirect
from django.views.generic       import TemplateView

import django.contrib.auth.views as auth_views
import feedback.urls
import settings


def signout(request):
    logout(request)
    return redirect( "/%s/" % request.GET.get( "app_name", "forms" ))


urlpatterns = [
    url( r'^logout/$',          signout),
    url( r'^password_change/$', auth_views.password_change ),
    url( r'^password_reset/$',  auth_views.password_reset, { 'extra_email_context': { 'protocol': 'https' } }, name='custom_password_reset' ),
    url( '',                    include( 'social.apps.django_app.urls', namespace='social')),
    url( '',                    include( 'django.contrib.auth.urls')),

    url( r'^$',                 lambda x:HttpResponseRedirect( '/forms/' )),
    url( r'^forms/',            include( feedback.urls, namespace="ncc-forms" )),
    url( r'^admin/doc/',        include( 'django.contrib.admindocs.urls' )),
    url( r'^admin/',            include( admin.site.urls )),

    url( r'^paypal/',           include( 'paypal.standard.ipn.urls', namespace="ncc-paypal" )),
    url( r'^o/',                include( 'oauth2_provider.urls', namespace='oauth2_provider' )),
    url( r'^api-auth/',         include( 'rest_framework.urls', namespace='rest_framework') ),
    url( r'^api/',              include( 'api.urls', namespace='api' )),
]

feedback/models.py
from    django.contrib.auth.models      import Group, User
from    django.contrib.sites.models     import Site
from    django.core.validators          import RegexValidator, URLValidator, validate_comma_separated_integer_list
from    django.db                       import models
from    django.db.models                import Q
from    django.db.utils                 import ProgrammingError
from    django.forms.models             import model_to_dict
from    django                          import forms

import  datetime
import  itertools
import  json
import  logging
import  os
import  re
import  sys

import  project.settings as settings

from    pdb import set_trace as st

#############################################

def get_user_group_names(user):
    return ( g.name for g in user.groups.order_by('name') )


def get_user_group_ids(user):
    return (g.pk for g in user.groups.all())


def get_user_ministries(user):
    return list({ name.split("-")[0] for name in get_user_group_names(user) if len(name.split("-")) > 1 })


def get_ministry_groups(ministry_list):
    qs  = ( Group.objects.filter( name__startswith=ministry ).order_by('name') for ministry in ministry_list )
    key = lambda obj: obj.name.lower()
    return sorted(
        itertools.chain.from_iterable(qs),
        key = key,
    )

def get_user_ministry_groups(user):
    return get_ministry_groups( get_user_ministries(user) )


def access_granted(user, group_ids):
    if user.is_superuser:  return True
    group_ids       = set( [ int(gid) for gid in group_ids.split(",") ] if group_ids else [] )
    user_group_ids  = set( get_user_group_ids(user) )
    return len( group_ids & user_group_ids )

#############################################

try:
    _sites = "(%s)" % ")|(".join( site.domain.strip() for site in Site.objects.all() )
except ProgrammingError:
    _sites = "(\.*)"

ncc_email_validator = RegexValidator( regex=".+\@%s" % _sites, message="NCC addresses only" )

ncc_url_validator   = URLValidator( regex="https?://(\w.*?\.)?%s/.+" % _sites, message="NCC URLs only" )

#############################################
class MyBaseModel(models.Model):
#############################################

    class Meta:
        abstract = True

    @classmethod
    def get( cls, key ):
        q = cls.objects.filter( **{cls.key_property: key} )
        try:    return q.get()
        except  cls.DoesNotExist:
                return None

    @classmethod
    def new( cls, key ):
        entity = cls()
        setattr( entity, cls.key_property, key )
        return entity

    def model_to_dict(self):
        return model_to_dict(self)



#############################################
class ChoiceCategories(MyBaseModel):
#############################################

    class Meta:
        verbose_name_plural = "Choice Categories"
        ordering            = [ "name", ]

    name = models.CharField( max_length=100, db_index=True )

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.strip()
        super(ChoiceCategories, self).save(*args, **kwargs)



#############################################
class Choices(MyBaseModel):
#############################################

    class Meta:
        verbose_name_plural = "Choices"
        ordering            = [ "choice_category", "sort_order", "name" ]

    choice_category = models.ForeignKey('ChoiceCategories', related_name="choices_set" )
    name            = models.CharField( max_length=100, db_index=True )
    responses_limit = models.IntegerField( default=0, blank=True )
    sort_order      = models.IntegerField( blank=True, default=99 )

    def __unicode__(self):
        return "%s : %s" % ( self.name, self.choice_category.name )

    def save(self, *args, **kwargs):
        self.name = self.name.strip()
        super(Choices, self).save(*args, **kwargs)



#############################################
class Projects(MyBaseModel):
#############################################

    class Meta:
        verbose_name_plural = "Forms"
        ordering            = ["reference"]

    PROJECT_STATUSES    = (
        ( -1, "Deleted" ),
        (  0, "Authenticated use" ),
        (  1, "Anonymous use" ),
    )

    key_property        = "reference"
    reference           = models.CharField( max_length=255, default="", unique=True, error_messages={"unique":"Duplicate reference"}, db_index=True  )
    description         = models.TextField( default="")
    status              = models.IntegerField( blank=True, null=True, default=1, choices=PROJECT_STATUSES, db_index=True )
    perms_read          = models.CharField(  max_length=255, blank=True, default="", validators=[validate_comma_separated_integer_list] )
    perms_write         = models.CharField(  max_length=255, blank=True, default="", validators=[validate_comma_separated_integer_list] )
    redirect_url        = models.URLField (    blank=True,    default="", validators=[ncc_url_validator] )
    redirect_text       = models.TextField(    blank=True,    default="" )
    expiry              = models.DateField(    blank=True,    null=True  )
    closure_url         = models.URLField (    blank=True,    default="", validators=[ncc_url_validator] )
    closure_text        = models.TextField(    blank=True,    default="" )
    max_feedbacks       = models.IntegerField( blank=True,    default=0  )
    max_feedbacks_url   = models.URLField (    blank=True,    default="", validators=[ncc_url_validator] )
    max_feedbacks_text  = models.TextField(    blank=True,    default="" )
    notify              = models.TextField(    blank=True,    default="" )
    template            = models.CharField(    blank=True,    max_length=255, default="default.html" )
    queue               = models.CharField(    blank=True,    max_length=255, default="" )
    ga_code             = models.CharField(    blank=True,    max_length=255, default="" )
    consent_page        = models.BooleanField( blank=True,    default=True )
    color_font          = models.CharField(    blank=True,    max_length=32, default="" )
    color_question      = models.CharField(    blank=True,    max_length=32, default="" )
    color_accent        = models.CharField(    blank=True,    max_length=32, default="" )
    created_by          = models.ForeignKey( User, blank=True, null=True )
    created_date        = models.DateTimeField( auto_now_add=True, blank=True, null=True )


    def __unicode__(self):
        return self.reference

    def can_read(self, group):
        perms = [int(perm) for perm in self.perms_read.split(",")] if self.perms_read else []
        return group.pk in perms

    def can_write(self, group):
        perms = [int(perm) for perm in self.perms_write.split(",")] if self.perms_write else []
        return group.pk in perms


#----------------------------
class ProjectForm(forms.ModelForm):
#----------------------------
    class Meta:
        model   = Projects
        exclude = []

    perms_read  = forms.MultipleChoiceField( widget=forms.SelectMultiple )
    perms_write = forms.MultipleChoiceField( widget=forms.SelectMultiple )


    def __init__(self, *args,  **kwargs):
        user = kwargs.pop("user")
        super(ProjectForm, self).__init__(*args, **kwargs)

        # groups
        groups = [ (group.pk, group.name) for group in get_user_ministry_groups(user) ]
        self.fields["perms_read"].choices  = groups
        self.fields["perms_write"].choices = groups

        # templates
        dirname     = os.path.dirname( sys.modules[__name__].__file__ )
        dirname     = os.path.join( dirname, "templates", "questionnaire" )
        templates   = [ ( t, t.split(".")[0] ) for t in os.listdir( dirname ) if t.endswith(".html") ]
        self.fields["template"].choices = templates


    def clean_perms_read(self):
        data = self.cleaned_data['perms_read']
        return ",".join( [str(v) for v in data] )


    def clean_perms_write(self):
        data = self.cleaned_data['perms_write']
        return ",".join( [str(v) for v in data] )


    def clean_notify( self ):
        data = self.cleaned_data['notify']
        if data:
            data = [ email.strip() for email in data.split("\n") ]
            [ ncc_email_validator( email ) for email in data ]
            return "\n".join( data )
        return data

#############################################
class Questions(MyBaseModel):
#############################################

    # names must be consistent with validators.js
    VALIDATORS = (
        ( "0",          "None"),
        ( "1",          "Unique"),
        ( "2",          "Email"),
        ( "3",          "NRIC/FIN"),
    )

    ANSWER_TYPES = [
        ("radio",           "Multiple choices - single answer"),
        ("multicheckbox",   "Multiple choices - multiple answers"),
        ("checkbox",        "Yes/No"),
        ("text",            "Single line text"),
        ("textarea",        "Multi-line text"),
        ("number",          "Number"),
        ("email",           "Email"),
        ("date",            "Date"),
        ("month",           "Month"),
        ("id",              "NRIC/FIN/Passport"),
        ("nric",            "NRIC/FIN"),
        ("label",           "Label"),
        ("readonly",        "Read-only"),
        ("hidden",          "Hidden"),
    ]
    if settings.PAYPAL_REDIRECT_HOSTNAME:
        ANSWER_TYPES.append( ("paypal", "Paypal") )

    CHOICE_TYPES = [
        "radio",
        "checkbox",
        "multicheckbox"
    ]

    OPTIONS_COLUMNS = [
        # Bootstrap grid
        ( 12, "1 column"     ),
        (  6, "2 columns"    ),
        (  4, "3 columns"    ),
        (  3, "4 columns"    ),
        ( -1, "Dropdown box" ),
    ]

    STRIPTAGS = re.compile("\<.+?\>")


    class Meta:
        verbose_name_plural = "Questions"
        ordering            = ["project", "question_no"]

feedback/templates/answers_edit.html
{% extends "base.html" %}

{% block    content %}


<div class="page-header clearfix">
    <h4>
        <div>{{answer.project.description}}</div><br>

        <div class="pull-left">Q#{{answer.question.question_no}}. &nbsp; </div>
        <div class="pull-left">{{answer.question.question | safe}}</div>
    </h4>
</div>

<p>


<div class="alert-danger">
    {{ form.non_field_errors }}
    {{ form.errors }}
</div>


<form action="." method="post">

    <div class="form-group">
        <label>Current Answer</label>
        <textarea name="old_answer" class="form-control" rows="5" readonly>{{ answer.answer }}</textarea>
    </div>

    <div class="form-group">
        <label>Data Change Reason</label>
        <textarea name="reason" class="form-control" rows="5" required></textarea>
    </div>

    <div class="form-group">
        <label>New Answer</label>
        <textarea name="new_answer" class="form-control" rows="5" required></textarea>
    </div>


    <button type="submit" class="btn btn-primary">Save</button>


    {{form.answer.as_hidden}}
    {{form.user.as_hidden}}
    {% csrf_token %}

</form>



{% endblock content %}

feedback/templates/answers_list.html
{% extends "base.html" %}

{% block    content %}

<style>
a.answer        { text-decoration: none }
.type_label     { display: none }
.type_hidden    { display: none }
.type_readonly  { display: none }
</style>

<div class="page-header clearfix">
    <h4>
        <span class="pull-left">{{project.description}}</span>
    </h4>
</div>

<div>
Total feedbacks : {{feedbacks.paginator.count}}
</div>

<p>

<table class="table table-hover table-striped table-responsive table-bordered">


<thead>
<tr>

    <th class="feedback_date">
    </th>

    {% for q in project.questions_set.all %}


        <th class="type_{{q.answer_type}}">
            <span class="question-no">
            {{q.question_no}}</span>.
            <span class="question-text">{{q.question | striptags |truncatechars:100}}</span>
        </th>

    {% endfor %}

</tr>
</thead>



<tbody>
{% for feedback in feedbacks %}
    <tr>

        <td class="feedback_date">
            {{ feedback.timestamp }}
        </td>

        {% for answer in feedback.answers_set.all %}
            <td class="type_{{answer.question.answer_type}}">
                <a href="{{answer.id}}" class="answer">
                    {{ answer.answer }}
                </a>
            </td>
        {% endfor %}

    </tr>
{% endfor %}
</tbody>


</table>



<div class="pagination" style="width:100%">
    <div class="step-links text-center">
        {% if feedbacks.has_previous %}
            <a class="btn btn-primary pull-left" href="?page={{ feedbacks.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ feedbacks.number }} of {{ feedbacks.paginator.num_pages }}.
        </span>

        {% if feedbacks.has_next %}
            <a class="btn btn-primary pull-right" href="?page={{ feedbacks.next_page_number }}">next</a>
        {% endif %}
    </div>
</div>

{% endblock content %}

feedback/templates/closed.html
{% extends "base.html" %}

{% block content %}
<div class="well">

{% if project.closure_text %}
    {{project.closure_text|safe}}

{% else %}
    <p>Thank you for connecting with us.</p>

    <p>This feedback link is now closed.</p>

    <p>Have a blessed day!</p>

{% endif %}

</div>
{% endblock content %}

feedback/templates/consent.html
<style>
div.checkbox.consent {
    padding-left:2em;
}
</style>
<div class="checkbox consent"><br>
    <input type="checkbox" name="Qconsent" required id="Q99999" ng-model="consent">
    <div class="consent">
        I agree to and accept the Privacy Policy and Terms of Use of this website.
        I consent that the personal information I provided in my capacity
        as a member of society, and other optional information I have chosen
        to provide such as my family details and photo(s) may be shared with
        others. My informationmay also be viewable on a limited and restricted basis on
        Internet sites. I may opt out of sharing my information or limit the
        optional information by duly informing the authorities.
    </div>
</div>

feedback/templates/feedback_list.html
{% extends "base.html" %}

{% block    content %}
<style>
.show-all {
    color:silver;
}
</style>

<div ng-app="forms.FeedbackList" ng-controller="feedbackListController as ctrl">

<div class="page-header clearfix">
    <h4>
        <a href="csv?{{ request.META.QUERY_STRING }}" class="pull-right" type="text/csv" download="feedbacks.csv">
            <span class="glyphicon glyphicon glyphicon-download-alt color-initial" title="CSV download data"></span>
        </a>

        <span
            class="pull-right glyphicon glyphicon-filter color-initial padding-right"
            ng-click="toggleShowAll()"
            ng-class="{ 'show-all':showAll }"
            title="Multiple choice answers only"
        ></span>

        <span class="pull-left">{{project.description}}</span>
    </h4>
</div>

<div>

    <button class="btn btn-default pull-right" ng-click="ctrl.refresh()"><span class="glyphicon glyphicon-refresh"></span></button>

    <div class="col-xs-3 pull-right margin-bottom-1">
        <div class="input-group">
            <span class="input-group-addon">To</span>
            <input class="form-control" ng-model="ctrl.dateTo" ng-init="django.dateTo" gn-date-picker>
        </div>
    </div>

    <div class="col-xs-3 pull-right">
        <div class="input-group">
            <span class="input-group-addon">From</span>
            <input class="form-control" ng-model="ctrl.dateFrom" gn-date-picker>
        </div>
    </div>

    <span class="pull-left">Feedbacks: {{feedbacks.count}}</span>
</div>

<p>

<table class="table table-hover table-striped table-responsive table-bordered">

<thead>
<tr>
    <th>Time</th>
    {% for answer in feedbacks.0.answers %}
        <th {% if not answer.question.is_choice_type %}ng-show="showAll"{% endif %}>Q{{answer.question.question_no}}</th>
    {% endfor %}
</tr>
</thead>


<tbody>
{% for feedback in feedbacks%}
<tr class="small">
    <td>
        <a href="{% url 'forms:feedback_answers' feedback.pk %}">
            <span class="inline-block width-2em text-right padding-right">{{forloop.counter}}.</span>
            {{feedback.timestamp}}
        </a>
    </td>

    {% for answer in feedback.answers %}
        <td {% if not answer.question.is_choice_type %}ng-show="showAll"{% endif %}>
            {{answer.answer}}
        </td>
    {% endfor %}
</tr>
{% endfor %}
</tbody>


</table>



<div class="modal fade" id="myModal">
<div class="modal-dialog">
<div class="modal-content">

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="chart-title"></h4>
    </div>

    <div class="modal-body text-center" id="chart-div">
    </div>

</div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->


</div><!-- ng-app -->
{% endblock content %}


{% block    postblockbody %}
<script src="/static/js/feedback/feedback_list.js"></script>
{% endblock postblockbody %}

feedback/templates/form_list.html
{% extends "base.html" %}

{% block    content %}
<div ng-app="forms" ng-controller="Feedback.projectsController">

<style>
.badge.in:hover {
    background-color:blue;
}
.glyphicon.pull-right:hover {
    color:blue;
}
.glyphicon.pull-right {
    padding-left:0.25em;
}
.card {
    margin:1.5em 0;
    box-shadow:0.2em 0.2em 0.5em silver;
}
</style>


<div class="page-header clearfix">
    <h4>
        <span class="pull-left">
            <select
                class="form-control"
                ng-model="group"
                ng-change="groupFilterChanged()"
                ng-show="data.groups.length > 1"
            >
                <option value="">All Teams</option>
                <option
                    ng-repeat="g in data.groups track by g.group_id"
                    ng-bind="g.name"
                    ng-value="g.group_id"
                    ng-selected="g.group_id == group"
                >
            </select>
        </span>

        {% if perms.feedback.add_projects %}
            <a class="btn btn-primary btn-lg pull-right" href="newform/" title="New form"><span class="glyphicon glyphicon-plus-sign"></span></a>
        {% endif %}

        <div class="dropdown col-xs-1 pull-right"  ondblclick="location='import/'">
            <button class="btn btn-default pull-right dropdown-toggle" type="button" data-toggle="dropdown" ng-bind="(status)?status:'All'"></button>
            <ul class="dropdown-menu" role="menu">
                <li><a role="menuitem" ng-click="status='Active'"   >Active</a></li>
                <li><a role="menuitem" ng-click="status='Expired'"  >Expired</a></li>
                <li><a role="menuitem" ng-click="status=''"         >All</a></li>
            </ul>
        </div>

        <div class="col-xs-4 pull-right">
            <div class="input-group">
                <span class="glyphicon glyphicon-search input-group-addon"></span>
                <input type="search" class="form-control" ng-model="search">
            </div>
        </div>

    </h4>
</div>


{% verbatim %}

<ul class="list-group">

        <li
            class="list-group-item card"
            ng-repeat="project in data.projects
                | orderBy:data.orderBy
                | filter:search
                | filter:{ active: status }
                | filter: groupFilter"
            ng-if="project.writable || project.readable"
            ng-cloak
        >
            <h4>

                <span ng-if="project.active=='Expired'">*</span>

                <span ng-show="project.writable">
                    <a href="editform/{{project.id}}/">
                        <span class="glyphicon glyphicon-edit" title="Edit questionnaire"></span>
                    </a>&nbsp;
                    <a
                        href="editform/{{project.id}}/"
                        title="Edit questionnaire"
                        style="color:dimgrey; font-weight:bold;"
                        >{{project.description}}
                    </a>
                </span>

                <span ng-hide="project.writable">{{project.description}}</span>
                &emsp;
                <span class="small">{{project.expiry|date:"d-MMM-yyyy"}}</span>

            </h4>
                <a href="/forms/{{project.reference}}/"><span class="glyphicon glyphicon-play" title="View questionnaire"></span></a>&nbsp;
                <a
                    href="/forms/{{project.reference}}/"
                    title="{{(project.active=='Active')?'View questionnaire':'Expired'}}"
                >
                    {{ origin }}/forms/{{project.reference}}
                </a>
                &emsp;
                <span class="small">{{project.latest|date:"d-MMM-yyyy HH:mm"}}</span>
                &emsp;
                <span ng-if="project.readable && project.feedback_count > 0">
                    <a
                        href="data/{{project.id}}/list"
                        title="Data list"
                    >
                        <span class="badge in" style="margin-top:-0.5em;">{{project.feedback_count}}</span
                    ></a>

                    <a
                        href="data/{{project.id}}/summary"
                        title="Data summary"
                    >
                        <i class="icon ion-pie-graph" style="font-size:1.25em"></i>
                    </a>
                </span> <!-- ng-if="project.readable" -->
        </li>
</ul>

{% endverbatim %}

</div> <!-- ng-app -->
{% endblock content %}


{% block script %}
<script src="/static/js/feedback/projects.js"></script>
{% endblock script %}

feedback/templates/piechart.html
{% extends "base.html" %}
{% load nvd3_tags %}


{% block    postblockhead %}
    {% include_chart_jscss %}
    {% load_chart charttype chartdata "piechart_container" kw_extra %}

    <style>
        body { background-color:transparent; }
    </style>
{% endblock postblockhead %}



{% block preblockbody %}

    {% if not fullscreen %}
        <button
            class="btn-link btn-sm glyphicon glyphicon-fullscreen small padding"
            title="Fullscreen"
            onclick="fullscreen( {{question.pk}} );"
            style="position:fixed; text-decoration:none; margin-top:-0.9em;"
        ></button>
    {% endif %}

    {% if header == 1 %}
        <div class="text-center padding" style="width:{{width|add:"-25"}}px;">
            <h5 class="inline"><strong>{{question.question | striptags}}</strong></h5>
            <span class="glyphicon glyphicon-cog pull-right" data-toggle="modal" data-target="#settingsModal" ></span>
        </div>
    {% endif %}
    {% include_container "piechart_container" height width %}


<div class="modal fade" id="settingsModal">
<div class="modal-dialog">
<div class="modal-content">

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Settings</h4>
    </div>

    <div class="modal-body">
        <form class="form-horizontal">
            <input type="hidden" name="f" value="1">

            <div class="form-group">
                <label for="inputCut" class="col-sm-2 control-label">Cut label at</label>
                <div class="col-sm-10">
                <input type="text" name="cut" class="form-control" id="inputCut">
                </div>
            </div>

            <div class="form-group">
                <label for="inputLength" class="col-sm-2 control-label">Label length</label>
                <div class="col-sm-10">
                <input type="number" name="length" class="form-control" id="inputLength" value="0" min="0">
                </div>
            </div>

            <div class="form-group">
                <label for="inputWidth" class="col-sm-2 control-label">Width</label>
                <div class="col-sm-10">
                <input type="number" name="width" class="form-control" id="inputWidth" value="{{width}}" min="350">
                </div>
            </div>

            <div class="form-group">
                <label for="inputHeight" class="col-sm-2 control-label">Height</label>
                <div class="col-sm-10">
                <input type="number" name="height" class="form-control" id="inputHeight" value="{{height}}" min="350">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Refresh</button>
                </div>
            </div>

        </form>
</div>

</div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>
function fullscreen(pk) {
    window.open( '{% url "forms:feedback_chart" %}' + pk + "/?f=1&width=800&height=800" );
    $("#myModal").modal('hide');
}
</script>

{% endblock preblockbody %}


{% block    header %}
{% endblock header %}